= Order Service =
{localdatetime}
:toc:
:doctype: book
:docinfo:

This microservice has born with the aim of placing a new order to get a seat
to see a good movie.

If you need more information you can take a look into:
https://refactorizando.com/patron-saga-quarkus-kafka

== Introduction

This microservice is responsible for receiving the request in json format for
take a seat. When the request is received, a transaction will be initiated for
achieve that goal.

== How does it work?

=== Run kafka
The first thing you need to do is launch a kafka broker that you can do with the following docker:

   docker run --rm -p 2181:2181 -p 3030:3030 -p 8081-8083:8081-8083 -p 9581-9585:9581-9585 -p 9092:9092 -e ADV_HOST=localhost landoop/fast-data-dev:latest

=== Run the application

==== Running the application in dev mode

You can run your application in dev mode that enables live coding using:
```shell script
./mvnw compile quarkus:dev
```

> **_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8090/q/dev/.

==== From your IDE

You can run your application using your IDE and running the class:
```shell script
AllocateApplication.java
```

==== Packaging and running the application

The application can be packaged using:
```shell script
./mvnw package
```
It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

If you want to build an _über-jar_, execute the following command:
```shell script
./mvnw package -Dquarkus.package.type=uber-jar
```

The application is now runnable using `java -jar target/quarkus-app/quarkus-run.jar`.

==== Creating a native executable

You can create a native executable using:
```shell script
./mvnw package -Pnative
```

Or, if you don't have GraalVM installed, you can run the native executable build in a container using:
```shell script
./mvnw package -Pnative -Dquarkus.native.container-build=true
```

You can then execute your native executable with: `./target/quarkus-saga-1.0.0-SNAPSHOT-runner`

=== Test the application

If you want to try and verify how it works you can use your postman and make a POST in http://localhost:8090/seats with the next body:

       {
        "id":1,
        "column": 1,
        "row":1,
        "user":{
          "id":1,
          "name":"noel"
          }
        }
